
import { Signika_Negative } from 'next/font/google'
import { Navigation } from '@/components/AppNavigation'
import { Header } from '@/components/Header'
import './globals.css'

const font = Signika_Negative({ weight: "300", style: "normal", display: 'swap', subsets: ['latin'] })

export const metadata = {
  title: 'My Pet organizer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        
          <Navigation />
          <div className='flex flex-col bg-slate-300 w-screen pb-20 md:pb-0'>
            <Header />
            {children}
          </div>
        
        </body>
    </html>
  )
}
