import './globals.css'
import { Signika_Negative } from 'next/font/google'
import Sidebar from '../components/Navigation'
import Header from '../components/Header'
const font = Signika_Negative({ weight: "300", style: "normal", display: 'swap', subsets: ['latin'] })
import { Routes } from '../components/routes'
export const metadata = {
  title: 'My Pet organizer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className='flex flex-1'>
          <Sidebar routes={[Routes.HOME, Routes.PROFILE, Routes.SIGN_OUT]} />
          <div className='flex flex-col bg-slate-300 w-screen pb-20 md:pb-0'>
            <Header />
            {children}
          </div>
        </div>
        </body>
    </html>
  )
}
