export {default as addPet} from './addPet.png'
export {default as arrowRight} from './arrowRight.svg'
export {default as grooming} from './grooming.png'
export {default as home} from './home.png'
export {default as logo} from './logo.png'
export {default as petFood} from './petFood.png'
export {default as petHealth} from './petHealth.png'
export {default as signUp} from './signUp.png'
